### ISSUE TITLE
Error when installing package

### ISSUE THREAD

**Issue by LucienHH** [extremeheat/node-leveldb-zlib#4]
Currently trying to install this package and get this error message:

```
Error: Could not locate the bindings file. Tried:
 → C:\Users\-\Documents\Discord\GitRepos\X-Bot\node_modules\leveldb-zlib\build\node-leveldb.node
 → C:\Users\-\Documents\Discord\GitRepos\X-Bot\node_modules\leveldb-zlib\build\Debug\node-leveldb.node
 → C:\Users\-\Documents\Discord\GitRepos\X-Bot\node_modules\leveldb-zlib\build\Release\node-leveldb.node
 → C:\Users\-\Documents\Discord\GitRepos\X-Bot\node_modules\leveldb-zlib\out\Debug\node-leveldb.node
 → C:\Users\-\Documents\Discord\GitRepos\X-Bot\node_modules\leveldb-zlib\Debug\node-leveldb.node
 → C:\Users\-\Documents\Discord\GitRepos\X-Bot\node_modules\leveldb-zlib\out\Release\node-leveldb.node
 → C:\Users\-\Documents\Discord\GitRepos\X-Bot\node_modules\leveldb-zlib\Release\node-leveldb.node
 → C:\Users\-\Documents\Discord\GitRepos\X-Bot\node_modules\leveldb-zlib\build\default\node-leveldb.node
 → C:\Users\-\Documents\Discord\GitRepos\X-Bot\node_modules\leveldb-zlib\compiled\14.16.0\win32\x64\node-leveldb.node
 → C:\Users\LucienHolloway\Documents\Discord\GitRepos\X-Bot\node_modules\leveldb-zlib\addon-build\release\install-root\node-leveldb.node
 → C:\Users\LucienHolloway\Documents\Discord\GitRepos\X-Bot\node_modules\leveldb-zlib\addon-build\debug\install-root\node-leveldb.node
 → C:\Users\LucienHolloway\Documents\Discord\GitRepos\X-Bot\node_modules\leveldb-zlib\addon-build\default\install-root\node-leveldb.node
 → C:\Users\LucienHolloway\Documents\Discord\GitRepos\X-Bot\node_modules\leveldb-zlib\lib\binding\node-v83-win32-x64\node-leveldb.node
    at bindings (C:\Users\LucienHolloway\Documents\Discord\GitRepos\X-Bot\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (C:\Users\LucienHolloway\Documents\Discord\GitRepos\X-Bot\node_modules\leveldb-zlib\binding.js:28:33)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at checkIfPrebuildExists (C:\Users\LucienHolloway\Documents\Discord\GitRepos\X-Bot\node_modules\leveldb-zlib\buildChecks.js:7:22)
    ```

**Comment by LucienHH** [comment]
So I didn't look at the error closely enough but I can see it starts to try builf=ding but crashes out when trying to run the cmake-js compile command `Error: Command failed: cmake-js compile` 

`ERR! OMG CMake is not installed. Install CMake.`

I have installed cmake to my machine so unsure why this may be occuring
